version: 1.2
workflows:
  - subclass: WDL
    primaryDescriptorPath: /vibecheck/workflows/classify.wdl
    name: vibecheck-lineage-assignment
    topic: Rapid classification of cholera genomes using phylogenetic placement.
    authors:
      - name: Nathaniel L. Matteson
        email: nmatteson@bwh.harvard.edu
  - subclass: WDL
    primaryDescriptorPath: /vibecheck/workflows/classify_reads.wdl
    name: vibecheck-lineage-assignment-reads
    topic: Rapid classification of cholera sequencing data using variant frequency demixing.
    authors:
      - name: Nathaniel L. Matteson
        email: nmatteson@bwh.harvard.edu
