version: 1.2
workflows:
  - subclass: WDL
    primaryDescriptorPath: /vibecheck/workflows/classify.wdl
    name: vibecheck-lineage-assignment
    authors:
      - name: Nathaniel L. Matteson
        email: nmatteson@bwh.harvard.edu
