name: vibecheck
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.11
  - usher
  - biopython
  - minimap2=2.28
  - rich
  - gofasta
  - pandas
  - freyja=1.5.3
  - bcftools
  - samtools
  - seqtk
  - pytest
  - pyarrow
