name: vibecheck
channels:
  - conda-forge
  - bioconda
dependencies:
  - python
  - usher
  - biopython
  - minimap2=2.28
  - rich
  - gofasta
  - pandas
  - bcftools
  - samtools
  - seqtk
  - pytest
  - pyarrow
  - joblib
  - tqdm
  - plotly
  - pyyaml
  - requests
  - epiweeks
  - pysam
  - seaborn-base
  - sphinx
  - sphinx_rtd_theme
  - pip:
      - "git+https://github.com/watronfire/Freyja.git@patch-3"
