name: Test the program
on:
  pull_request:
    paths-ignore:
      - '.*'
      - '.github/**'
      - 'LICENSE'
      - 'pyproject.toml'
      - 'README.md'
      - 'vibecheck/workflows/**'
  push:
    paths-ignore:
      - '.*'
      - '.github/**'
      - 'LICENSE'
      - 'pyproject.toml'
      - 'README.md'
      - 'vibecheck/workflows/**'
  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ "ubuntu-latest" ]

    steps:
      - name: Checkout source
        uses: actions/checkout@v4
      - uses: mamba-org/setup-micromamba@v1
        with:
          cache-environment: true
          environment-file: test_environment.yaml
      - name: Run tests
        run: micromamba run -n vibecheck python -m pytest --rootdir=. . --junitxml=junit/test-results.xml
